### ISSUE TITLE
Etapa 1: Inicialização do kernel

### ISSUE THREAD

**Issue by kailanyas** [kailanyas/kernel-OS#1]
Nesta etapa, é necessário implementar a inicialização básica do kernel. Isto inclui a configuração do ambiente de desenvolvimento e a configuração do bootloader (GRUB). Ademais, é relevante testar a inicialização para garantir que o kernel inicie corretamente. 

**Tarefas**
- [x] Configurar ambiente de desenvolvimento
- [x] Configurar o bootloader (GRUB)
- [x] Testar a inicialização para garantir que o kernel inicie corretamente

**Responsável:** [Thiago Tonelli](https://github.com/ThiagoTonelli)

**Comment by ThiagoTonelli** [comment]
Feito :)
