### ISSUE TITLE
Etapa 5: Implementando funções de impressão na tela

### ISSUE THREAD

**Issue by kailanyas** [kailanyas/kernel-OS#12]
Para conseguirmos imprimir mensagens na tela, é necessário criar algumas funções. Essas funções serão implementadas no arquivo `scrn.c`.

**Tarefas**

- [x] Criar arquivo `scrn.c`
- [x] Implementar funções de imprimir na tela
- [x] Adicionar as declarações das funções em `system.h`

**Comment by ThiagoTonelli** [comment]
Lembre-se de incluir o arquivo `scrn.c` na lista de arquivos a serem linkados (build.sh).
