### ISSUE TITLE
Etapa 6: Implementando a Tabela Global de Descritores (GDT)

### ISSUE THREAD

**Issue by ThiagoTonelli** [kailanyas/kernel-OS#13]
Criar a Tabela Global de Descritores (GDT), responsável por gerenciar segmentos de memória no modo protegido. Para isso, as funções implementadas serão criadas no arquivo `gdt.c`.

**Tarefas**

- [x] Criar o arquivo `gdt.c`
- [x] Implementar funções responsável por gerenciar a memória
- [x] Incluir declarações no `system.h`
- [x] Incluir `gdt.c` na lista de arquivos a serem linkados (`build.sh`)

**Comment by kailanyas** [comment]
Feito! :+1:
