### ISSUE TITLE
Etapa 8: Implementação das Rotinas de Serviço de Interrupção (ISRs)

### ISSUE THREAD

**Issue by kailanyas** [kailanyas/kernel-OS#15]
Implementar rotinas de serviço de interrupção (ISRs) para gerenciar as interrupções e IRQs no kernel. Para isso, deve-se criar o arquivo `isrs.c`.

**Tarefas**

- [x] Criar arquivo `isrs.c`
- [x] Implementar as funções para ISRs
- [x] Adicionar o cabeçalho das funções em `system.h`
- [x] Incluir `isrs.c` em `build.sh` para ser compilado

**Comment by ThiagoTonelli** [comment]
Feito! 👍
