### ISSUE TITLE
Etapa 11: Gerenciando o teclado

### ISSUE THREAD

**Issue by ThiagoTonelli** [kailanyas/kernel-OS#18]
Nessa etapa, é gerenciado as entradas obtidas do teclado, a partir de interrupções. Isso inclui a leitura dos scancodes quando uma tecla é pressionada e a conversão desses scancodes em caracteres ASCII. Com isso, é possível escrever na tela.

**Tarefas**

- [x] Criar um arquivo `kb.c`
- [x] Implementar as funções que gerenciam as entradas do teclado
- [x]  Adicionar o cabeçalho das funções em `system.h`
- [x] Incluir isrs.c em `build.sh` para ser compilado

**Comment by kailanyas** [comment]
Pronto! :+1:
