### ISSUE TITLE
Etapa 3: Implementar a função main() e funções básicas

### ISSUE THREAD

**Issue by kailanyas** [kailanyas/kernel-OS#3]
Implementar a função `main()` como ponto de entrada para o código em C, junto com algumas funções básicas, como `strlen`. Também é necessário criar o arquivo de cabeçalho `system.h` para declarações.

**Tarefas:**
- [x] Criar arquivo `main.c`
- [x] Implementar algumas funções básicas (como `strlen`)
- [x] Implementar função `main()`

**Comment by ThiagoTonelli** [comment]
Foi implementado! É necessário a atualização da `main()` de acordo com o desenvolvimento do projeto.
